PLENTY-271-finalization
findologic/plentymarkets-rest-exporter-new pull request #13
Opened 2020-10-23 15:09 UTC by RimantasAdeoWeb

2020-10-27 09:40 UTC, TheKeymaster requested changes

2020-10-27 09:40 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +            $orderNumbers = array_merge($orderNumbers, $this->getVariationOrdernumbers($variation));
Please write `ordernumber` as a single word, since we should try to always use the same wording.

2020-10-27 09:40 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +            $orderNumbers[] = (string)$variation->{$getter}();
See my other comment regarding `ordernumber`.

2020-10-27 09:40 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        $orderNumbers = array_unique($orderNumbers);
Good idea to make them unique here.

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +            \DateTime::createFromFormat(\DateTime::ISO8601, $item->getDateAdded()->getValues()['']) !== false
Please import this.

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +        $entries[0]['tags'] = [
Is the index really necessary here?

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +        $variationResponse['entries'] = $entries;
This bloat distracts a bit from the actual test. Can't this be set in a separate response directly? This way the test data and the actual test is separated.

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +        $variationResponse['entries'] = $entries;
Please do this for all tests.

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/VariationTest.php
> +        $this->expectException(\TypeError::class);
Please import this.

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/VariationTest.php
> +        $this->expectException(\TypeError::class);
When I expect an exception I typically add it to the top of the test. This way the next developer immediately sees that I expect an exception here.

2020-10-27 09:40 UTC, TheKeymaster commented on tests/Wrapper/VariationTest.php
> +        $this->expectException(\TypeError::class);
Would this exception cause an export to fail? So if my shop had a vat id of `10`, would this break the export?

2020-10-28 10:19 UTC, RimantasAdeoWeb commented on tests/Wrapper/VariationTest.php
> +        $this->expectException(\TypeError::class);
Yes, it would cause it to fail completely.
I also noticed that the old exporter actually takes the vat rate from the LAST variation of an item, not the first. I'll update this exporter to match the old one in this regard.
Another problem is that the old exporter would export nothing in the vat rate column in a case like this here. The libflexport exports an unset taxrate as 0. Is this difference ok?

2020-10-28 11:34 UTC, TheKeymaster commented on tests/Wrapper/VariationTest.php
> +        $this->expectException(\TypeError::class);
> Yes, it would cause it to fail completely.

This is something we should avoid. I have already seen that you have changed it, but in the future we should make sure that the exporter only fails in a managed manner, and not due to some cryptic type error.

Only developers know what's wrong when checking the logs, but also others should read and understand the logs without the need of manually checking the code (if they even have dev experience).

> When changing this, I've noticed a few things:
I also noticed that the old exporter actually takes the vat rate from the LAST variation of an item, not the first. I'll update this exporter to match the old one in this regard.

That's a good call, since we want the new exporter to return the same data as the old one.

> Another problem is that the old exporter would export nothing in the vat rate column in a case like this here. The libflexport exports an unset taxrate as 0. Is this difference ok?

Yes this is fine, as libflexport should handle this right. If it turns out that this may cause issues at customers, we may need a change in libflexport, but for now this shouldn't be a problem.

2020-10-28 11:37 UTC, TheKeymaster approved these changes

2020-11-04 08:43 UTC, merged