PLENTY-301 use old url format if configured to do so
findologic/plentymarkets-rest-exporter-new pull request #22
Opened 2021-02-08 14:17 UTC by RimantasAdeoWeb

2021-02-08 14:19 UTC, RimantasAdeoWeb commented on src/RegistryService.php
> +    public function fetchPluginConfigurations(): void
I really hated having to make this method public, but otherwise I would have had to restructure way too many things to make it testable. Would have taken forever or longer.

2021-02-09 09:31 UTC, TheKeymaster commented on src/RegistryService.php
> +                if (str_starts_with($e->getMessage(), 'The REST client does not have access rights for method')) {
I am surprised, how can this even work? We use PHP 7.3 in our test runs and this method is a PHP 8.0 method. Please check this.

2021-02-09 09:36 UTC, TheKeymaster commented on src/RegistryService.php
> +            } catch (Exception $e) {
Can't the `Client` throw an `AccessDeniedException` or some sort? This would make this easier to implement. Also if we had other routes in the future, where we want to fail gracefully, we would have an easier way of adding such a functionality.

2021-02-09 09:38 UTC, TheKeymaster commented on src/Request/PluginConfigurationRequest.php
> +        parent::__construct('GET', "plugins/{$pluginId}/plugin_sets/{$pluginSetId}/configurations");
A few years back, this would've been considered dangerous, but now with types, this is actually quite useful.

2021-02-09 09:38 UTC, TheKeymaster commented on src/Response/Collection/PluginConfigurationResponse.php
> +    public function all(): array
Missing return docblock.

2021-02-09 09:39 UTC, TheKeymaster commented on src/Response/Collection/PluginFromSetResponse.php
> +    public function all(): array
Missing return docblock.

2021-02-09 09:41 UTC, TheKeymaster commented on src/Response/Entity/Plugin.php
> +            foreach ($data['containers'] as $container) {
Have a look at `Entity::getEntities`, which may come in this class.

2021-02-09 09:43 UTC, TheKeymaster commented on src/Response/Entity/Plugin.php
> +     * @return array
Here are a few unnecessary returns of `array`. Do we know the structure? Otherwise drop that docblock.

2021-02-09 09:44 UTC, TheKeymaster commented on src/Response/Entity/Plugin/UpdateInformation.php
> +    public function getUpdateVariationId()
`mixed|null`?

2021-02-09 09:45 UTC, TheKeymaster commented on src/Response/Entity/PluginConfiguration.php
> +    /**
Add newlines after property declarations.

2021-02-09 09:45 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        return filter_var($configs['Ceres']['global.enableOldUrlPattern'], FILTER_VALIDATE_BOOLEAN);
Neat usage of `FILTER_VALIDATE_BOOLEAN` :+1:

2021-02-09 09:47 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        if (!isset($configs['Ceres']['global.enableOldUrlPattern'])) {
Can we have a helper to get the Ceres plugin? Doesn't need to be exactly in the `RegistryService`, but should be available where any class would be able to access it.

2021-02-09 09:50 UTC, TheKeymaster commented on tests/RegistryServiceTest.php
> +                $this->throwException(new \Exception('The REST client does not have access rights for method asdasd')),
`\Exception` may be imported.

2021-02-09 09:51 UTC, TheKeymaster commented on tests/Response/Collection/PluginConfigurationResponseTest.php
> +    private $pluginConfigurationResponse;
Please add docblock types.

2021-02-09 09:52 UTC, TheKeymaster commented on tests/Response/Collection/PluginConfigurationResponseTest.php
> +    public function testResponseSearchFunctions(): void
This is an odd test name. I can not really grasp what it actually tests.

2021-02-09 09:52 UTC, TheKeymaster commented on tests/Response/Collection/PluginFromSetResponseTest.php
> +    private $pluginResponse;
Please add docblock types.

2021-02-09 09:52 UTC, TheKeymaster commented on tests/Response/Collection/PluginFromSetResponseTest.php
> +    public function testResponseSearchFunctions(): void
See my other comment.

2021-02-09 09:53 UTC, TheKeymaster commented on tests/Response/Collection/PluginFromSetResponseTest.php
> +                0 => '4090',
You do not need to provide an index.

2021-02-09 09:54 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +    public function testCallistoUrlFormatIsUsedWhenConfiguredToDoSo(): void
Please drop `ToDoSo`. Makes this test name a bit cleaner.

2021-02-09 09:55 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +        $text = new Text([
This `Text` is being used quite often. Can we add a helper to generate it, as it basically is the same code over and over again.

2021-02-09 09:56 UTC, TheKeymaster commented on tests/Response/Collection/PluginFromSetResponseTest.php
> +                0 => '4090',
Happened quite a lot in this file, please remove all the indexes.

2021-02-09 15:34 UTC, RimantasAdeoWeb commented on tests/Wrapper/ProductTest.php
> +        $text = new Text([
Each test uses it a bit differently though. It would have to use so many parameters, it would probably look even worse.

2021-02-09 16:05 UTC, RimantasAdeoWeb commented on src/Wrapper/Product.php
> +        if (!isset($configs['Ceres']['global.enableOldUrlPattern'])) {
Modified the registry getter to make it easier to get the configs of a specific plugin

2021-02-09 16:07 UTC, RimantasAdeoWeb commented on src/Registry.php
> +     * @return mixed
Yup, this will now need to store arrays also. Updated the `set` method.

2021-02-09 16:07 UTC, RimantasAdeoWeb commented on src/RegistryService.php
> +                if (str_starts_with($e->getMessage(), 'The REST client does not have access rights for method')) {
Good catch. I've changed it to the good ol' strpos just in case

2021-02-10 09:20 UTC, TheKeymaster requested changes

2021-02-10 09:20 UTC, TheKeymaster commented on src/Exception/PermissionException.php
> +class PermissionException extends Exception
Can this exception extend from `CustomerException`? This way the type doesn't change. A `CustomerException` may always be thrown if configuration or common issues occur, which the customer is able to check out his own.

2021-02-10 09:20 UTC, TheKeymaster commented on src/RegistryService.php
> +            } catch (PermissionException $e) {
That's a cleaner read :+1:

2021-02-10 09:20 UTC, TheKeymaster commented on tests/Response/Collection/PluginFromSetResponseTest.php
> +     * @var \GuzzleHttp\Psr7\Response
This may be imported.

2021-02-15 13:41 UTC, TheKeymaster approved these changes

2021-02-15 13:42 UTC, merged