PLENTY-248 upgrade PHP version
findologic/plentymarkets-rest-exporter-new pull request #23
Opened 2021-04-01 12:16 UTC by RimantasAdeoWeb

2021-04-01 14:26 UTC, TheKeymaster requested changes

2021-04-01 14:26 UTC, TheKeymaster commented on composer.json
> +        "phpunit/phpunit": "^9.5"
This looks like it has been manually edited, or somehow updated, without also updating the `composer.lock` file. 
Please run `composer require --dev phpunit/phpunit:^9.5 --with-all-dependencies` to update PHPUnit.

Even though it is not strictly part of this story, please install `symfony/phpunit-bridge` as a dev dependency. Once installed, we are automatically informed after each test run, if we still use stuff, which is considered deprecated.

As of PHPUnit 9.3 for example, [the `->at()` method has been deprecated](https://github.com/sebastianbergmann/phpunit/issues/4297), which we should take care of.

2021-04-09 12:37 UTC, RimantasAdeoWeb commented on composer.json
> +        "phpunit/phpunit": "^9.5"
Omg why would they deprecate it...
"it can lead to brittle tests which are too closely tied to specific implementation details" my ass, when the suggested alternative is specifying the entire sequence of params and returns anyway.

2021-04-12 11:05 UTC, TheKeymaster approved these changes

2021-04-12 11:05 UTC, TheKeymaster commented on composer.json
> +        "symfony/phpunit-bridge": "^5.2"
:raised_hands:

2021-04-12 11:09 UTC, TheKeymaster commented on composer.json
> +        "phpunit/phpunit": "^9.5"
Changing it like that makes you force writing cleaner code. It can be quite tricky for an existent code base with bad code, there will be hard times refactoring a simple `->at()` to a big `->exactly(xx)->withConsecutive()`.

But we are lucky, as we only used `->at()` twice in our code, and having a good code base :+1:!

2021-04-12 11:11 UTC, merged