PH-37 Fix open REST exporter issues
findologic/plentymarkets-rest-exporter-new pull request #24
Opened 2021-04-19 16:35 UTC by TheKeymaster

2021-04-21 16:06 UTC, dblaichinger requested changes

2021-04-21 16:06 UTC, dblaichinger commented on tests/RegistryServiceTest.php
> +        $this->registryService->warmUp();
"...AndExportContinues" 

How does the test ensure that the export continues?

2021-04-22 08:09 UTC, TheKeymaster commented on src/Response/Entity/Pim/Property/Image.php
> +    private ?int $position;
No this should be an iterative process. That would take way too much time.

2021-04-22 08:10 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        if (!$hasCategories) {
A product could have multiple variants. We only want to skip a product if **all variants** have no categories.

2021-04-22 08:11 UTC, TheKeymaster commented on tests/RegistryServiceTest.php
> +        $this->registryService->warmUp();
If it wouldn't continue, an exception would be thrown. Here we explicitly ensure that the line `This causes multiSelect properties to not be exported!` is logged.

2021-04-22 08:12 UTC, TheKeymaster commented on src/Exporter/Exporter.php
> +            'verify' => false,
Yes some Plenty customers (also in the past) and also our x1 demo shop (currently) have had an invalid certificate. Also we do not care if a customer has an invalid certificate or not, we just want to get the data from the REST API.

2021-04-22 08:13 UTC, TheKeymaster commented on src/Response/Entity/WebStore/Configuration.php
> +        $itemMeasureUnitData = $data['itemMeasureUnit'] ?? null;
`itemMeasureUnit` could not exist at all, therefore using `??` prevents any bugs.

2021-04-22 08:17 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +                $this->item->addSort($variation->getPosition() ?? 0);
The fun thing is that libflexport default value for sort is `null`, but calling `addSort` requires an `int`. We could not call this method all together, or just set this to `0`. I do not have a strong opinion on either of them.

2021-04-22 08:22 UTC, dblaichinger commented on src/Wrapper/Product.php
> +                $this->item->addSort($variation->getPosition() ?? 0);
I would rather set no sort if we don't have a position. The actual fix should be made in libflexport by setting `?int`.

2021-04-22 10:52 UTC, dblaichinger approved these changes

2021-04-22 12:30 UTC, merged