PLENTY-336_allow_custom_file_name
findologic/plentymarkets-rest-exporter-new pull request #28
Opened 2021-04-23 07:42 UTC by TheKeymaster

2021-04-23 09:46 UTC, dblaichinger requested changes

2021-04-23 09:46 UTC, dblaichinger commented on composer.lock
> +            "version": "v2.9.0",
It seems like the version is not set in composer.json

2021-04-23 09:46 UTC, dblaichinger commented on tests/UtilsTest.php
> +        $request = new PluginConfigurationRequest(1234, 1234);
Let's call it `$nonIterableRequest` to make it clear.

2021-04-23 10:27 UTC, closed without merging

2021-04-26 07:28 UTC, TheKeymaster commented
Closed in favor of #29.