PLENTY-319 ability to export variations with groupable attributes as separate items
findologic/plentymarkets-rest-exporter-new pull request #31
Opened 2021-06-07 10:25 UTC by RimantasAdeoWeb

2021-06-07 13:50 UTC, TheKeymaster requested changes

2021-06-07 13:50 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +        bool $separateVariationMode = false
I prefer not having such boolean parameters. Why not have a `int $mode` parameter? We could then simply say `Mode::DEFAULT` and `Mode::SEPARATE_VARIATIONS`. This way we could also add more modes in the future.

2021-06-07 13:50 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +        }
Can we simplify this a bit? I need to understand both loops in order to know why we have `continue 2` here.

2021-06-07 13:50 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +    private function splitVariationsByGroupability(array $productVariations): array
Maybe we can add a bit of context in the docblock, which describes the behavior a bit better.

2021-06-07 13:50 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +        return $config['item.variation_show_type'] == 'all';
Please also put `all` as a separate constant somewhere.

2021-06-07 13:50 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +                if ($item = $this->doWrap($product, $groupedVariations)) {
Can we have a bit more defensive coding here? Nested `if`s are kind of hard to get into.

2021-06-07 13:50 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +    private $separateMode;
We use PHP 7.4, so this could be properly typehinted as `int` (see my comment regarding modes).

2021-06-07 13:50 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +    public function testItExportsEachVariationSeparatelyIfConfiguredToDoSoAndIfAllVariationsHaveAGroupableAttribute()
We can get rid of `It` as a test always describes "`a`" behavior. Also `ToDoSo` isn't really a clear description of what the test should actually do. Why not call it something like `testGroupableVariantsAreExportedAsSeparateItemsWhenConfigured`. Maybe you can come up with a name that is shorter or even more expressive.

2021-06-07 13:50 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +                $this->callback(function ($items) {
You can actually typehint `array $items`

2021-06-07 13:50 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +    public function testItExportsTwoItemsWhenOnlyOneOutOfThreeVariantsHasGroupableAttributes()
Please see my comment above regarding test names. This applies to all tests in this class.

2021-06-07 13:50 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +                    'item.variation_show_type' => 'notAll'
Is it really `notAll`? In my other comment I asked to add a constant for `all` so it probably also makes sense to create one for `notAll` as well (if this is actually how Plenty named this).

2021-06-07 13:50 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +                $this->callback(function ($items) {
See my other comment regarding the callback function type hints. This applies to all newly added callbacks.

2021-06-08 10:26 UTC, RimantasAdeoWeb commented on tests/Wrapper/CsvWrapperTest.php
> +                    'item.variation_show_type' => 'notAll'
Naw, they have multiple options there, there's no actual 'notAll'. Do I make this 'anyConfigValueAsLongAsItIsNotAll' to make it clearer?

2021-06-08 12:21 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +                    'item.variation_show_type' => 'notAll'
Can't we just use the option provided by Plenty if it is indeed not `all`, what would this be and can we use that?

2021-06-09 12:16 UTC, merged