Plenty 347
findologic/plentymarkets-rest-exporter-new pull request #33
Opened 2021-07-21 15:13 UTC by RimantasAdeoWeb

2021-07-21 15:14 UTC, RimantasAdeoWeb commented on src/Response/Collection/PropertySelectionResponse.php
> +            if ($relationValue) {
Couldn't use `if ($relationValue = Translator:...)` syntax because apparently PHPStan can't connect docblocks to such variable declarations.

2021-07-26 07:22 UTC, TheKeymaster requested changes

2021-07-26 07:22 UTC, TheKeymaster commented on src/Parser/PropertySelectionParser.php
> +            (int)$response['totalsCount'],
Do we need those casts for other response instances as well?

2021-07-26 07:22 UTC, TheKeymaster commented on src/Response/Collection/PropertySelectionResponse.php
> +            if ($relationValue) {
:+1:

2021-07-26 07:22 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +                continue;
Nice catch! Can we add a unit-test, so we don't remove this again by accident in the future?

2021-07-26 07:22 UTC, TheKeymaster commented on src/Wrapper/Variation.php
>              $this->tags[] = new Keyword($tagName);
Wouldn't this cause an exception when `$translatedTag` returns `null`, as `$tagName` is never declared?

2021-07-28 10:46 UTC, RimantasAdeoWeb commented on src/Wrapper/Variation.php
>              $this->tags[] = new Keyword($tagName);
$tagName is declared a few lines above.

2021-07-28 11:28 UTC, RimantasAdeoWeb commented on src/Parser/PropertySelectionParser.php
> +            (int)$response['totalsCount'],
No, probably a bug in the Plentymarkets API with this endpoint.

2021-07-28 12:24 UTC, TheKeymaster approved these changes

2021-07-28 12:36 UTC, merged