Plenty 369
findologic/plentymarkets-rest-exporter-new pull request #40
Opened 2021-09-14 08:55 UTC by RimantasAdeoWeb

2021-09-14 10:56 UTC, TheKeymaster requested changes

2021-09-14 10:56 UTC, TheKeymaster commented on src/Response/Collection/PropertyGroupResponse.php
> +        int   $itemsPerPage = 100
These indents were probably added by accident?

2021-09-14 10:56 UTC, TheKeymaster commented on src/Response/Entity/ItemPropertyGroup/Name.php
> +        $this->propertyGroupId = (int)$data['propertyGroupId'];
Can't we use `getIntProperty` here?

2021-09-14 10:56 UTC, TheKeymaster commented on src/Response/Entity/ItemPropertyGroup/Name.php
> +        return (string)$this->lang;
Wouldn't this be more explicit?

```suggestion
        return $this->lang ?? '';
```

2021-09-14 10:56 UTC, TheKeymaster commented on src/Wrapper/PropertyAware.php
> +            if (!$value && $property->getPropertyData()->getCast() == CastType::EMPTY) {
I know in the old exporter we weren't strict about this, but we should change that, because it is a string comparison anyway

```suggestion
            if (!$value && $property->getPropertyData()->getCast() === CastType::EMPTY) {
```

2021-09-14 10:56 UTC, TheKeymaster commented on src/Wrapper/PropertyAware.php
> +                    [$property->getValues()[0]],
Are we sure that the first index will always exist here?

2021-09-14 10:56 UTC, TheKeymaster commented on src/Wrapper/PropertyAware.php
> +                $value = $this->registryService->getPropertySelections()->getPropertySelectionValues(
We can be explicit about the naming, because `$value` isn't very descriptive. I need to check the method name in line 77 to know for what this value is used, but I would still have no idea where this is coming from, when I am checking this from line 106.

```suggestion
                $propertySelectionValues = $this->registryService->getPropertySelections()->getPropertySelectionValues(
```

This makes it also clearer, why we are using `reset($value)` at the end, as it contains an array of selection values.

2021-09-14 10:56 UTC, TheKeymaster commented on tests/Response/Collection/ItemPropertyGroupResponseTest.php
> +        date_default_timezone_set('Europe/Vienna');
Please set this in the boostrap of all tests (`tests/bootstrap.php`), as this should be either done for all or for no tests. If you don't want this, we should then ensure to reset this to how it was before in `tearDown`, as otherwise this may impact some tests and not others, which you will only notice much later down the line, when you already spent endless time debugging.

2021-09-14 10:56 UTC, TheKeymaster commented on tests/Response/Collection/ItemPropertyGroupResponseTest.php
> +    public function testGetAllReturnsCorrectNumberOfItems()
Please check the tests to always include a typehint.

2021-09-14 10:56 UTC, TheKeymaster commented on tests/Response/Collection/PropertyGroupResponseTest.php
> -        date_default_timezone_set('Europe/Vienna');
I guess this was the issue that I was talking about in my previous comment. It's better to move this in the bootstrap.

2021-09-15 07:28 UTC, RimantasAdeoWeb commented on src/Wrapper/PropertyAware.php
> +                    [$property->getValues()[0]],
Yes

2021-09-15 09:33 UTC, TheKeymaster approved these changes

2021-09-15 09:37 UTC, merged