PLENTY-338 add a referrer id config to export only properties with a …
findologic/plentymarkets-rest-exporter-new pull request #43
Opened 2021-09-30 12:35 UTC by RimantasAdeoWeb

…matching referrer

2021-09-30 13:04 UTC, TheKeymaster requested changes

2021-09-30 13:04 UTC, TheKeymaster commented on src/RegistryService.php
> +            if ($option->getType() !== 'referrers') {
Do we know which types exist? Im not a big fan of floating strings. Stuff like this should be in a separate class. See `\FINDOLOGIC\PlentyMarketsRestExporter\Definition\CastType` for example.

2021-09-30 16:12 UTC, RimantasAdeoWeb commented on .env
> +# EXPORT_REFERRER_ID must be either NULL or a number with two decimals in string format, e.g. '10.00'
Here's the response:
```
{"page":1,"totalsCount":6,"isLastPage":true,"lastPageNumber":1,"firstOnPage":1,"lastOnPage":6,"itemsPerPage":"100","entries":[{"id":1,"cast":"selection","type":"item","position":0,"createdAt":"2021-07-15T11:35:07+01:00","updatedAt":"2021-07-15T11:35:07+01:00","names":[{"id":9,"propertyId":1,"lang":"en","name":"Color","description":"Color","createdAt":"2021-07-15T11:35:07+01:00","updatedAt":"2021-07-15T11:35:07+01:00"}],"amazon":[{"id":11,"propertyId":1,"platform":"de","category":"AutoAccessory","field":"item_name","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"}],"options":[{"id":876,"propertyId":1,"type":"clients","value":"37811","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":877,"propertyId":1,"type":"display","value":"displayInOrderProcess","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":878,"propertyId":1,"type":"display","value":"showInItemListing","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":879,"propertyId":1,"type":"display","value":"showInPDFDocuments","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":880,"propertyId":1,"type":"display","value":"showOnItemsPage","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":881,"propertyId":1,"type":"displayOrder","value":"orderProperty","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":882,"propertyId":1,"type":"referrers","value":"0.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":883,"propertyId":1,"type":"referrers","value":"1.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":884,"propertyId":1,"type":"referrers","value":"101.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":885,"propertyId":1,"type":"referrers","value":"102.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":886,"propertyId":1,"type":"referrers","value":"103.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":887,"propertyId":1,"type":"referrers","value":"104.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":888,"propertyId":1,"type":"referrers","value":"104.01","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":889,"propertyId":1,"type":"referrers","value":"104.02","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":890,"propertyId":1,"type":"referrers","value":"104.03","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":891,"propertyId":1,"type":"referrers","value":"104.04","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":892,"propertyId":1,"type":"referrers","value":"104.05","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":893,"propertyId":1,"type":"referrers","value":"104.06","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":894,"propertyId":1,"type":"referrers","value":"104.07","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":895,"propertyId":1,"type":"referrers","value":"104.08","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":896,"propertyId":1,"type":"referrers","value":"104.21","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":897,"propertyId":1,"type":"referrers","value":"104.22","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":898,"propertyId":1,"type":"referrers","value":"105.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":899,"propertyId":1,"type":"referrers","value":"106.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":900,"propertyId":1,"type":"referrers","value":"106.02","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":901,"propertyId":1,"type":"referrers","value":"107.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":902,"propertyId":1,"type":"referrers","value":"108.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":903,"propertyId":1,"type":"referrers","value":"108.02","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":904,"propertyId":1,"type":"referrers","value":"109.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":905,"propertyId":1,"type":"referrers","value":"110.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":906,"propertyId":1,"type":"referrers","value":"111.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":907,"propertyId":1,"type":"referrers","value":"112.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":908,"propertyId":1,"type":"referrers","value":"113.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":909,"propertyId":1,"type":"referrers","value":"114.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":910,"propertyId":1,"type":"referrers","value":"115.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":911,"propertyId":1,"type":"referrers","value":"116.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":912,"propertyId":1,"type":"referrers","value":"117.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":913,"propertyId":1,"type":"referrers","value":"118.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":914,"propertyId":1,"type":"referrers","value":"119.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":915,"propertyId":1,"type":"referrers","value":"120.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":916,"propertyId":1,"type":"referrers","value":"121.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":917,"propertyId":1,"type":"referrers","value":"121.02","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":918,"propertyId":1,"type":"referrers","value":"122.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":919,"propertyId":1,"type":"referrers","value":"123.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":920,"propertyId":1,"type":"referrers","value":"124.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":921,"propertyId":1,"type":"referrers","value":"125.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":922,"propertyId":1,"type":"referrers","value":"126.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":923,"propertyId":1,"type":"referrers","value":"127.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":924,"propertyId":1,"type":"referrers","value":"130.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":925,"propertyId":1,"type":"referrers","value":"131.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":926,"propertyId":1,"type":"referrers","value":"132.00","createdAt":"2021-09-24T14:17:04+01:00","updatedAt":"2021-09-24T14:17:04+01:00"},{"id":927,"propertyId":1,"type":"referrers","value":"133.00","createdAt":"2021 [...]

2021-10-01 07:06 UTC, TheKeymaster commented on .env
> +# EXPORT_REFERRER_ID must be either NULL or a number with two decimals in string format, e.g. '10.00'
But how or where can a customer see this in his backend?

2021-10-01 07:11 UTC, RimantasAdeoWeb commented on .env
> +# EXPORT_REFERRER_ID must be either NULL or a number with two decimals in string format, e.g. '10.00'
The ID column:
![image](https://user-images.githubusercontent.com/61787115/135579986-73021c90-98cb-40b0-b87c-affa63dab56e.png)

2021-10-01 07:25 UTC, TheKeymaster commented on .env
> +# EXPORT_REFERRER_ID must be either NULL or a number with two decimals in string format, e.g. '10.00'
I see, these are the values. My last question would then be, if the values that have no numbers at the end, such as customly-added ones, are also suffixed with `11.00` for example? Or do they simply stay `11`?

If there will be no suffixes, please also somehow reflect this in the comment, otherwise this may be confusing for people that see this for the first time.

![image](https://user-images.githubusercontent.com/20555112/135581589-07033158-5b2d-4dbc-a508-87030db923c3.png)

2021-10-01 08:54 UTC, RimantasAdeoWeb commented on .env
> +# EXPORT_REFERRER_ID must be either NULL or a number with two decimals in string format, e.g. '10.00'
Eh, I just made the checking less strict, converting the given values to float. Should make it easier.

2021-10-04 08:57 UTC, TheKeymaster requested changes

2021-10-04 08:57 UTC, TheKeymaster commented on src/Config.php
> +    public function setExportReferrerId($id): void
We should have at least some idea what this value could or should be. Maybe it even makes sense to describe the value in a bit more detail here.

```suggestion
    /**
     * @var string|int|float $id
     */
    public function setExportReferrerId($id): void
```

2021-10-04 09:08 UTC, TheKeymaster approved these changes

2021-10-04 10:24 UTC, merged