PLENTY-400 fixing image uri
findologic/plentymarkets-rest-exporter-new pull request #53
Opened 2021-12-03 14:55 UTC by msilinskas

2021-12-07 09:49 UTC, TheKeymaster requested changes

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/CsvWrapper.php
> +                    (string)$key
Why is this casted to a string?

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        string $variationAttributes = ''
The name of this variable suggests an array, but it really is a string. Please try to find a better fitting name and rename it in other places accordingly.

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +        }
This is nested in a way which makes it honestly really hard to read. Try to exit early and apply some defensive coding, instead of nesting if blocks in further if blocks.

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +    private function checkImageAvailability(array $imageAttributeValues, array $variationAttributes): bool
A method that returns a boolean typically indicates a state of something. Such as `isAvailable` or `hasValues`. Without checking the method I wouldn't really know what it "checks", so please try to find a better fitting name.

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +    private function setImageForSeparatedVariation(array $images, array $variationAttributes): void
When using the `array` type always add the structure of it to the docblock. Please do this for all methods.

```php
/**
 * @param Entity[] $entities
 */
public function someMethod(array $entities): void
{
    // ...
}
```

The only exception to this rule is where an array structure may be too complex, where a docblock serves not much purpose, such as:

![image](https://user-images.githubusercontent.com/20555112/145004992-d1b9007e-b993-429a-b18f-6c770e682910.png)

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +        return $count === count($variationAttributes);
Without knowing deep internals, I would never know what this does. Try to move all things related to the separate variation logic into a separate class, which is responsible for it. Right now the code seems to creep up everywhere.

2021-12-07 09:49 UTC, TheKeymaster commented on tests/Response/Collection/PimVariationResponseTest.php
> +        unset($expectedImageData['updatedAt']);
Unsetting this twice won't do much :D

2021-12-07 09:49 UTC, TheKeymaster commented on tests/Wrapper/CsvWrapperTest.php
> +                        $this->assertEquals($expectedImagesUrls[$key], $columnValues[10]);
When the type is clear, I typically prefer `assertSame`, but this is also fine.

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +        }
Maybe this foreach logic can somehow be centeralized, as it is very similar to `setImageAvailabilityForDefaultWrapMode`.

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +                if ($imageAttributeId == $attributeData[0] && $imageValueId == $attributeData[1]) {
Why aren't you using strict comparison (`===`)?

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +    private function setImageAvailabilityForDefaultWrapMode(array $images): void
This method name would make me assume it is setting some availability for images, but instead it is actually setting the first image which is available for the store.

2021-12-07 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +        return $count === count($variationAttributes);
This class should also contain the logic to build the key, parsing the key and generally everything related to those separated variations.

2021-12-08 12:51 UTC, msilinskas commented on src/Wrapper/CsvWrapper.php
> +                    (string)$key
Sometimes key is a product id, which has a type of int

2021-12-08 14:43 UTC, msilinskas commented on src/Wrapper/Variation.php
> +                if ($imageAttributeId == $attributeData[0] && $imageValueId == $attributeData[1]) {
Sometimes exploded data has different type than data fetched from the image object.

2021-12-08 14:48 UTC, msilinskas commented on src/Wrapper/Variation.php
> +    private function setImageAvailabilityForDefaultWrapMode(array $images): void
This method was removed and the logic was nested with the separated vartiations logic.

2021-12-09 09:48 UTC, TheKeymaster requested changes

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        string $variationAttributeKey = ''
I would rather name this `$variationGroupKey`, as it references a grouped variation.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +    public function getVariationGroupKey(): string
Please add a docblock of how these may look like for different scenarios and also elaborate on how this structure is being made.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +     * @param array $variationAttributes
Isn't his a key/value of strings?

```suggestion
     * @param array<string, string> $variationAttributes
```

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +    private Variation $variation;
I typically prefer no spaces between class properties when they're strictly typed by PHP. But that's just preference.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +                if ($imageAttributeId != $variationAttributeId || $imageValueId != $variationValueId) {
Why aren't you using a strict comparison?

```suggestion
                if ($imageAttributeId !== $variationAttributeId || $imageValueId !== $variationValueId) {
```

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +        return ($groupableAttributes === 0 || count($attributeValues) > 1) ? $key : (string)$this->variation->getId();
This might be more readable with an if.

```suggestion
        if ($groupableAttributes === 0 || count($attributeValues) > 1)   {
            return $key;
        }

        return (string)$this->variation->getId();
```

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +            if ($attribute && $attribute->isGroupable()) {
This may be easier readable by skipping early. This also prevents those nested if blocks.
```suggestion
            if (!$attribute || !$attribute->isGroupable()) {
                continue;
            }
```

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +
Maybe this line can be removed to move the structurally dependent things more together.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +                return;
Those returns after setting the image instances seem a bit wrong. Maybe you want to add a method, which is responsible for getting the image. `processImages` would then be simply responsible for setting it to this class property.

```suggestion
    private function processImages(): void
    {
        $this->image = $this->getVariantImage();
    }
```

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +    protected $variationAttributesKey;
These class properties can also be typed.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +                    $key .= '/';
This feels like it wants to be a constant.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +                $key .= $attributeValue->getId() . '_' . $attributeValue->getValue()->getId();
`_` feels like it wants to be a constant.

2021-12-09 09:48 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +        return $count === count($variationAttributes);
As already noted, maybe a docblock would make it easier to understand.

2021-12-09 09:49 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +                if ($imageAttributeId == $attributeData[0] && $imageValueId == $attributeData[1]) {
Wouldn't it make more sense to add a typecheck or cast the values to their respective type?

2021-12-09 12:06 UTC, msilinskas commented on src/Wrapper/SeparatedVariation.php
> +     * @param array $variationAttributes
Nop, it hasa value like [0] => '112_150', [1] => '113_140'

2021-12-09 12:12 UTC, msilinskas commented on src/Wrapper/Variation.php
> +                return;
We need to stop the execution when image is set to an object

2021-12-09 12:42 UTC, msilinskas commented on src/Wrapper/Variation.php
> +        return $count === count($variationAttributes);
I've added a docblock.

2021-12-09 12:42 UTC, msilinskas commented on src/Wrapper/Variation.php
> +                if ($imageAttributeId == $attributeData[0] && $imageValueId == $attributeData[1]) {
I've added a type casts for the values

2021-12-09 13:18 UTC, TheKeymaster requested changes

2021-12-09 13:18 UTC, TheKeymaster commented on src/Wrapper/SeparatedVariation.php
> +     * @param array $variationAttributes
My point is, if we know what values it may contain, we should definitely typehint it. So it would be `array<int, string>` ot `string[]` then.

2021-12-09 13:18 UTC, TheKeymaster commented on src/Wrapper/Variation.php
> +                return;
Yes this is why I would like this to be a method that returns it instead of setting it and returning and therefore stopping further execution. Maybe this example makes it a bit more clear :D

```php
private function processImages(): void
{
    $this->image = $this->getVariantImage();
}

private function getVariantImage(): Image
{
    // foreach ...
    if ($this->wrapMode === Product::WRAP_MODE_DEFAULT) {
        return new Image($image->getUrlMiddle());
    }
    // ...
}
```

2021-12-09 14:37 UTC, TheKeymaster approved these changes

2021-12-09 14:43 UTC, merged