PLENTY-416_variation_id_in_url_depending_on_config
findologic/plentymarkets-rest-exporter-new pull request #57
Opened 2022-01-11 16:55 UTC by dblaichinger

2022-01-12 14:35 UTC, TheKeymaster requested changes

2022-01-12 14:35 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        $this->plentyShopConfig = $this->registryService->getPluginConfigurations('Ceres');
Can we change the existing calls in this class to now use the private property instead?

2022-01-12 14:35 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +            if (filter_var($this->plentyShopConfig['item.show_please_select'], FILTER_VALIDATE_BOOLEAN)) {
I think there is already another place where we use this `filter_var`. Can we generalize this in a static helper method, maybe in `Utils`?

2022-01-12 14:35 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +    public function itemShowPleaseSelectProvider()
Add missing typehint

```suggestion
    public function itemShowPleaseSelectProvider(): array
```

2022-01-12 14:35 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +        $expectedProductUrl
Add missing typehints.

2022-01-12 14:35 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +            'Url with variation id when "item.show_please_select" disabled' => [
I usually prefer having all data provider names being lower cased, as then, if the test would fail, everything is lower cased. But that's just my opinion.

![image](https://user-images.githubusercontent.com/20555112/149159930-332c650d-ab47-4d6b-95f5-3c4f5c965de0.png)

2022-01-12 14:35 UTC, TheKeymaster commented on tests/Wrapper/ProductTest.php
> +    /**
Please add a blank line between a new block/method.

2022-01-12 15:52 UTC, dblaichinger commented on src/Wrapper/Product.php
> +        $this->plentyShopConfig = $this->registryService->getPluginConfigurations('Ceres');
`$this->plentyShopConfig` is used in the class, see `shouldUseCallistoUrl()` or `getPlentyShopUrl()`. Or what do you mean exactly?

2022-01-13 08:58 UTC, TheKeymaster commented on src/Wrapper/Product.php
> +        $this->plentyShopConfig = $this->registryService->getPluginConfigurations('Ceres');
Ah nevermind, the second call for this is being done in `CsvWrapper` and everything else already accesses this information via `$this->plentyShopConfig`.

2022-01-13 08:58 UTC, TheKeymaster approved these changes

2022-01-13 09:01 UTC, merged