Plenty 471 upgrade the exporter to libflexport v3
findologic/plentymarkets-rest-exporter-new pull request #82
Opened 2023-05-12 08:32 UTC by Mariusslo

2023-06-02 07:22 UTC, TobiasGraml11 requested changes

2023-06-02 07:22 UTC, TobiasGraml11 commented on .vscode/launch.json
Please remove the `.vscode` folder and add it to the `.gitignore` file

2023-06-02 07:22 UTC, TobiasGraml11 commented on src/Request/ItemRequest.php
> +        ?int $id = 107,
```suggestion
        ?int $id = null,
```

2023-06-02 07:22 UTC, TobiasGraml11 commented on src/Exporter/CsvExporter.php
We can remove the `CsvExporter` and it's helper classes (if some exist). We won't add support for it with libflexport v3 anyway.

2023-06-02 07:22 UTC, TobiasGraml11 commented on src/Command/ExportCommand.php
> +        switch ($exporterType) {
Let's remove the command option entirely and write the code like only XML exists.

2023-06-02 07:22 UTC, TobiasGraml11 commented on phpunit.xml.dist
> +</phpunit>
Please add a newline to the end of the file

2023-06-02 07:22 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            }
There is already an image added at line 233, we should probably combine those.

2023-06-02 07:22 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            $this->item->setOverriddenPrice(new OverriddenPrice());
1. There is no value set here
2. Please rename all occurrences of `insteadPrice` to `overriddenPrice`

2023-06-02 07:22 UTC, TobiasGraml11 commented on tests/Command/ExportCommandTest.php
> +     * @dataProvider exportTypesProvider
After getting rid of the CSV part, we can change everything to XML-only here as well

2023-06-02 07:22 UTC, TobiasGraml11 commented on tests/Exporter/ExporterTest.php
> +        $this->fileExporterMock = LibFlexportExporter::create(ExporterType::CSV);
CSV is still used here

2023-06-02 07:22 UTC, TobiasGraml11 commented on tests/Helper/ItemHelper.php
Great helper class :+1:

2023-06-02 07:22 UTC, TobiasGraml11 commented on tests/Wrapper/ProductTest.php
> +        // $this->assertEquals(100, $item->getInsteadPrice()); //Temporarily remove because the fn doesnt exist anymore
Please change the test function to test the `overriddenPrice`

2023-06-02 07:22 UTC, TobiasGraml11 commented on tests/Wrapper/ProductTest.php
> +            'cat_url' => '/wohnzimmer/sessel-hocker/', 'free1' => '0000000000'
```suggestion
            'cat_url' => '/wohnzimmer/sessel-hocker/',
            'free1' => '0000000000'
```

2023-06-07 10:31 UTC, rimvydas-hashtages commented
@TobiasGraml11 you can now review the changes

2023-06-12 09:52 UTC, TobiasGraml11 requested changes

2023-06-12 09:52 UTC, TobiasGraml11 commented on src/Command/ExportCommand.php
> +
This function still has an `$exporterType`argument, we can remove that as well.

2023-06-12 09:52 UTC, TobiasGraml11 commented on src/Command/ExportCommand.php
> +            Exporter::TYPE_XML
We can remove this whole `addOption` block.

2023-06-12 09:52 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +                $this->item->setAllImages($variation->getImages());
Let's remove the `elseif` block and keep the logic as it is right now.
Right now, it is handled within `$cheapestVariations->addImageAndPrice`, instead of an additional `elseif`.

2023-06-12 09:52 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            $overriddenPrice->setValue(min($insteadPrices));
Please rename `$insteadPrices` to `$overriddenPrices`

2023-06-12 09:52 UTC, TobiasGraml11 commented on .env
> +ACCOUNT_PAT="xRPBSki22bzO75sOfehYjN0m12BBZia7RwfKyURS"
We should not commit any PAT, especially not within public repositories.

Please remove this and remove/regenerate the token from your account.

2023-06-12 10:30 UTC, rimvydas-hashtages commented on .env
> +ACCOUNT_PAT="xRPBSki22bzO75sOfehYjN0m12BBZia7RwfKyURS"
Can I rename this to .env.example and add .env to gitignore? Because thats usually how I do to avoid this

2023-06-12 10:31 UTC, TobiasGraml11 commented on .env
> +ACCOUNT_PAT="xRPBSki22bzO75sOfehYjN0m12BBZia7RwfKyURS"
Sure, let's do it like that

2023-06-12 10:32 UTC, rimvydas-hashtages commented on src/Wrapper/Product.php
> +                $this->item->setAllImages($variation->getImages());
without the elseif block it wouldnt pass because it checks $useCallistoUrl there

2023-06-12 10:33 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +                $this->item->setAllImages($variation->getImages());
Yeah, that's how it was done before as well. I don't want to change too much logic within this story.
If the check does not pass, it should just add the default image at a later stage, like it is done right now.

2023-06-13 07:55 UTC, rimvydas-hashtages commented on src/Wrapper/Product.php
> +                $this->item->setAllImages($variation->getImages());
Then data provided in the tests must be wrong cause it keeps failing the tests
![image](https://github.com/findologic/plentymarkets-rest-exporter/assets/83945230/4539e837-871f-485f-bb69-33f664c1a219)

2023-06-13 08:21 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +                $this->item->setAllImages($variation->getImages());
The expected value was changed within the data provider. We will need to revert that change.

2023-06-13 08:41 UTC, rimvydas-hashtages commented on src/Wrapper/Product.php
> +                $this->item->setAllImages($variation->getImages());
Okay changed it. You can review the PR again

2023-06-13 10:17 UTC, TobiasGraml11 requested changes

2023-06-13 10:17 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            $overriddenPrices[] = $variation->getInsteadPrice();
This function still includes `insteadPrice`

2023-06-13 10:17 UTC, TobiasGraml11 commented on tests/Command/ExportCommandTest.php
> +     * @dataProvider exportTypesProvider
We can get rid of this data provider now, as it only has one value anyway

2023-06-13 10:17 UTC, TobiasGraml11 commented on tests/Exporter/ExporterTest.php
> -            'Exporter type is CSV' => [
Please completely remove the data provider

2023-06-13 10:45 UTC, rimvydas-hashtages commented on src/Wrapper/Product.php
> +            $overriddenPrices[] = $variation->getInsteadPrice();
?

2023-06-13 11:54 UTC, TobiasGraml11 approved these changes

2023-06-13 15:46 UTC, merged