Plenty 392 exprt xml variants
findologic/plentymarkets-rest-exporter-new pull request #84
Opened 2023-08-02 11:42 UTC by aserstobitov

2023-08-02 11:53 UTC, TobiasGraml11 requested changes

2023-08-02 11:53 UTC, TobiasGraml11 commented on composer.json
> +        "findologic/libflexport": "3.1.0",
```suggestion
        "findologic/libflexport": "^3.1",
```

2023-08-02 11:53 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            // );
Why is this commented out here?

2023-08-02 11:53 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            // $parentId = $variants[$cheapestVariation[CheapestVariation::VARIATION_ID]];
Please check all the commented out code

2023-08-11 07:41 UTC, rimvydas-hashtages commented on src/Wrapper/Product.php
> +            // );
If I remember correctly, that function doesn't really go well with variant export because this fn adds images also to the item, which we do not need in that moment. Cheapest variants are added in line 327 above

2023-08-11 08:04 UTC, TobiasGraml11 commented on src/Wrapper/Product.php
> +            // );
If it is not needed anymore, please remove the code block, instead of commenting it out

2023-08-18 08:23 UTC, rimvydas-hashtages commented
@TobiasGraml11 you can review the changes again. It seems code coverage shrunk a bit I could also take a look at that issue if its not satisfactory.

Click-tests:
[xmls.zip](https://github.com/findologic/plentymarkets-rest-exporter/files/12377177/xmls.zip)

2023-08-18 09:05 UTC, TobiasGraml11 requested changes

2023-08-18 09:05 UTC, TobiasGraml11 commented on tests/Wrapper/ProductVariantsTest.php
> +        // TODO: check item's attributes property directly once attributes getter is implemented
There is still one TODO here.

Please check if there are still other TODOs left.

2023-08-28 07:35 UTC, TobiasGraml11 approved these changes

2023-09-07 07:08 UTC, TobiasGraml11 approved these changes

2023-09-07 08:03 UTC, merged