PLENTY-489-retry-requests-with-exceptions
findologic/plentymarkets-rest-exporter-new pull request #95
Opened 2024-05-22 06:23 UTC by aserstobitov

2024-05-22 13:27 UTC, TobiasGraml11 requested changes

2024-05-22 13:27 UTC, TobiasGraml11 commented on src/Client.php
> +        try {
It's probably best to wrap this inside a do...while instead of recalling the function again with an already adapted request class.

Something like:
```php
do {
    try {
        $response = $this->sendRequest($request, $request->getParams());
        $this->handleResponse($request, $response);

        return $response;
    } catch (...) {
        // log error

        // increment

        // sleep
    }
} while (!$request->isRetryLimitReached());

throw new Exception('Maximum retry limit reached without success');
```

2024-05-22 13:27 UTC, TobiasGraml11 commented on src/Request/Request.php
> +        return false;
```suggestion
        return $this->retryCounter >= self::MAX_RETRIES;
```

2024-05-22 13:27 UTC, TobiasGraml11 commented on tests/ClientTest.php
> +                'expectedCallTimes' => 2
Shouldn't it only be called once, if the exception is non-retryable?

2024-05-22 13:30 UTC, aserstobitov commented on tests/ClientTest.php
> +                'expectedCallTimes' => 2
@TobiasGraml11 It's called 2 times because the 1st time it needs to login, and 2nd time is the actual request

2024-05-22 13:31 UTC, TobiasGraml11 commented on tests/ClientTest.php
> +                'expectedCallTimes' => 2
Ok, makes sense 👍

2024-05-27 07:57 UTC, TobiasGraml11 requested changes

2024-05-27 07:57 UTC, TobiasGraml11 commented on src/Request/Request.php
> +        return $this->retryCounter == self::RETRY_LIMIT;
We need to make sure to also check the higher counts, in case the increment function is even slightly misused in future changes.

```suggestion
        return $this->retryCounter >= self::RETRY_LIMIT;
```

2024-05-27 10:20 UTC, TobiasGraml11 approved these changes

2024-05-27 12:13 UTC, merged